<html>
    <?php
    include 'entête.php';   
    ?>
<head>
        <title>Lakers</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="../cssboot/bootstrap.min.css" >
        <link rel="stylesheet" href="../css/Histoire.css">
        <link rel="icon" href="../images/Logo.png">
</head>
<body>
    <!--C'est le plan, avec les ancres.-->
            <div  class="container">
            <div class="row">
                <div class="col-8">
                    <h1 id="ancre13">Histoire des Lakers</h1>
                    <ol type="A">
                        <li> <a href="#ancre1">Gems de Détroit </a></li>
                        <li> <a href="#ancre2">Lakers de Minneapolis </a></li>
                        <li> <a href="#ancre3">Lakers de Los Angeles </a></li>
                        <ol type="1">
                            <li> <a href="#ancre4">Les débuts : longue course vers le titre (1960-1972) et période d'accalmie (1972-1980) </a></li>
                            <li> <a href="#ancre5">Le Show Time (1980-1991) </a></li>
                            <li> <a href="#ancre6">L'affaire du siècle mais toujours pas de confirmation (1996-1999) </a></li>
                            <li> <a href="#ancre7">La dynastie du nouveau millénaire et le duo Shaq & Kobe (1999-2004) </a></li>
                            <li> <a href="#ancre8">Les Lakers en perte de vitesse : L'ère « post-Shaq » (2004-2007) </a></li>
                            <li> <a href="#ancre9">Le retour du succès de l'équipe : L'ère Bryant-Gasol (2007-2011) </a></li>
                            <li> <a href="#ancre10">La reconstruction : Nash, Howard et D'Antoni (2012-2016) </a></li>
                            <li> <a href="#ancre11">Les Lakers de LeBron James (depuis 2018) </a></li>
                        </ol>
                        <li> <a href="#ancre12">Palmarès </a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!--Détail de l'Histoire des Lakers-->
        <hr>
        <div  class="container">
            <div class="row">
                <div  class="text-center">
                    <h1>Histoire de la Franchise</h1>
                    <ol type="A">
                        <li id="ancre1"><h5>Gems de Détroit</h5></li>
                            <p>La franchise est fondée en 1946, à Dearborn, Michigan sous le nom de Detroit Gems et évolue dans la National Basketball League (NBL). L'unique saison se finit par un triste bilan de 4 victoires pour 40 défaites. L'année suivante, l'équipe est rachetée par Ben Berger et Morris Chalfen qui délocalisent la franchise à Minneapolis. Ils en profitent pour renommer l'équipe en Lakers se référant aux nombreux lacs dans la région de Minneapolis (Lakers signifiant en anglais les « habitants des lacs »).</p>
                                    <hr>
                        <li id="ancre2"><h5>Lakers de Minneapolis</h5></li>
                            <img class="col-4 img-fluid" src="../images/MPLS.jpg" class="rounded">
                            <p>Il faut alors reconstruire totalement l'équipe. En ayant le pire bilan de la National Basketball League, les Lakers obtiennent le premier tour de draft en 1947 de la Professional Basketball League of America. Le choix se porte sur George Mikan. Ce dernier montre tout de suite son grand talent et permet à l'équipe de remporter cette même saison, son premier titre NBL. L'année suivante, la franchise change de ligue et intègre la Basketball Association of America (BAA). Grâce à Mikan et à une bonne alchimie, les Lakers remportent un nouveau titre, moins d'un an après être arrivés dans la ligue. Le mouvement dans les ligues est important à l'époque, car chacune tente d'attirer les meilleurs joueurs, d'où une forte concurrence.
                                Cependant en 1949 la NBL et la BAA s'unissent pour former la NBA. Ce qui n'empêche pas les Lakers de gagner leur premier titre de champion NBA un an plus tard. Cependant, ils ne réussiront pas le Four-Ever : le titre leur échappe l'année suivante en faveur des Rochester Royals. Les Lakers se consoleront en remportant trois titres consécutifs les trois saisons suivantes. En 1954, Mikan prend sa retraite à cause d'une blessure. Ce départ se fait cruellement ressentir sur le jeu des "hommes des lacs". Ajouté à cela, l'équipe rencontre des problèmes d'adaptation aux nouvelles règles instaurées par la NBA (règle 24 secondes et nombre de fautes limité à six). Même avec une brève tentative de retour de Mikan, qui finit par définitivement abandonner les parquets en 1956, les Lakers n'y arrivent pas. Minneapolis n'est plus la terreur des parquets.
                                Après cette courte période dans l'ombre (1954-1957), les Lakers reviennent au sommet en 1957, même si leur épopée se termine par une défaite en finale contre les Saint-Louis Hawks. À la suite de cet échec, Mikan devient l'entraîneur de l'équipe. Le résultat est désastreux, à tel point qu'il est limogé en cours de saison. Minneapolis, avec un bilan de 19 victoires pour 53 défaites ne participe pas aux play-offs. Néanmoins ce triste bilan leur permet d'obtenir le premier choix lors de la draft de 1958. Les Lakers choisissent Elgin Baylor, excellent scoreur qui leur permet d'atteindre la finale la saison suivante, face aux Celtics de Boston.
                                Au début des années 1960, l'intérêt pour la franchise diminue dû au fait que Mikan ne soit plus dans l'équipe. La franchise avait déjà failli déménager à Kansas City en 1957 après le rachat par Bob Short. Voyant que l'intérêt des fans est toujours aussi bas, la franchise s'exile définitivement de Minneapolis en 1960 pour rejoindre Los Angeles. La NBA ne revient dans le Minnesota qu'en 1989 avec la nouvelle franchise des Timberwolves du Minnesota.</p>
                                    <hr>
                        <li id="ancre3"><h5>Lakers de Los Angeles</h5></li>
                            <p>Voici le début de l'ascension des Lakers.</p>
                                    <hr>
                        <ol type="1">
                            <li id="ancre4"><h5>Les débuts : longue course vers le titre (1960-1972) et période d'accalmie (1972-1980)</h5></li>
                                    <img class="col-2 img-fluid" src="../images/JerryWest.jpg" class="rounded">
                                <p>Les Lakers arrivent donc à Los Angeles, après avoir écarté des villes comme San Francisco ou Chicago. Les Lakers deviennent la première équipe de la côte ouest. Los Angeles voit alors l'arrivée du meneur talentueux Jerry West. Le duo West-Baylor redonne de grands espoirs de titre aux fans de la franchise. Cependant le duo va être séparé car Baylor est appelé pour son service militaire, ce qui lui fait manquer une grande partie de la saison. Malgré cela, l'équipe atteint les finales mais perd lors du dernier match face aux Celtics. C'est le point de départ d'une grande rivalité sportive entre ces deux formations. Le rendez-vous est pris pour l'année suivante : les deux mêmes équipes se retrouvent en finale, et encore une fois les Celtics sont trop forts. En 1964, la franchise est éliminée avant les finales, mais ce n'est que partie remise puisque les Lakers vont atteindre les finales NBA les deux saisons suivantes. Néanmoins, ils seront, à chaque fois, incapables de battre les Celtics de Boston.
                                    Joueur de face, dribblant de la main droite, protégeant de son bras gauche un adversaire sur son coté.
                                    Jerry West en 1971.
                                    En dehors des parquets Bob Short vend l'équipe à Jack Kent Cooke pour 5 millions de dollars en 1965. Malgré sa défaite en finale de division en 1967, la franchise continue à jouer les premiers rôles dans la ligue. De plus l'arrivée de Wilt Chamberlain en 1968 est vue comme un signe d'espoir. En effet, certains voient en lui l'arme pour enfin réussir à battre les Celtics de Bill Russell. De 1968 à 1970, les Lakers atteignent les finales et l'histoire ne change pas : défaites face à Boston en 1968 et 1969 et face aux Knicks de New York en 1970. La saison 1971 est une année de transition. Le bilan est difficile, 7 finales perdues en 9 ans, il faut enfin vaincre cette malédiction en finale depuis l'arrivée de la franchise dans la côte ouest.
                                    La saison 1972 est celle du renouveau, et reste gravée dans les mémoires des fans des Lakers. L'équipe emmenée par Bill Sharman, qui est nommé entraîneur de l'année à l'issue de la saison, aligne une série de 33 victoires consécutives. Un record NBA qui tient toujours à l'heure actuelle et qui est sûrement très difficile à battre. Et cerise sur le gâteau, les Lakers empochent enfin leur premier titre depuis le déménagement de la franchise à Los Angeles.</p>
                                    <hr>
                            <li id="ancre5"><h5>Le Show Time (1980-1991)</h5></li>
                                <img class="col-6 img-fluid" src="../images/showtime.jpg" class="rounded">
                                <p>Pourtant et en dépit du recrutement du pivot Kareem Abdul-Jabbar, les Lakers devront attendre la saison 1979-1980 et l'arrivée de Magic Johnson pour remporter un nouveau titre. Lors des finales NBA 1980, ils dominent les 76ers de Philadelphie en six manches, en grande partie grâce à leur rookie Magic Johnson. Lors du sixième match, ce dernier joue à tous les postes, principalement pivot en raison de l'absence de Kareem Abdul-Jabbar blessé à la cheville pendant le cinquième match2. Magic termine la partie avec 42 points, 15 rebonds et 7 passes décisives2. Cette prestation est encore vue aujourd'hui comme la plus grande performance individuelle en finale NBA.
                                    Cette victoire marque le début de la période du Show Time, surnom donné à l'équipe des Lakers pendant les années 1980 en raison de son jeu à la fois spectaculaire et efficace, dit run and gun, fait de contre-attaques endiablées dirigé par Magic Johnson associé à Kareem Abdul-Jabbar, Jamaal Wilkes, Bob McAdoo, James Worthy et Byron Scott.
                                    Sous la direction de Pat Riley, les Lakers vont dominer les années 1980 en remportant cinq finales sur neuf, en 1980, 1982, 1985, 1987 et 1988, et en participant en tout à huit finales sur dix.
                                    Durant cette domination, les Lakers seront en grande rivalité avec les Celtics de Boston de Larry Bird, jouant notamment contre eux trois finales, en 1984, 1985 et 1987. Les 1984 NBA Finals resteront comme un des sommets de toute l'histoire des sports collectifs aux États-Unis, tant le style, les valeurs et les qualités des équipes sont opposées. D'un côté l'ouest, le soleil, la Californie, le strass, le showtime, une équipe composée de joueurs athlétiques et talentueux au sein d'une ville à majorité protestante. De l'autre, la côte est, le trèfle, le catholicisme, une équipe qui s'appuie sur un collectif léché et rigoureux, à l'image de la grisaille associée à cette région. Une couverture médiatique sans précédent pour un duel de légende, la finale ne se dénouant qu'au septième match avec la victoire de Boston.</p>
                                    <hr>
                           <li id="ancre6"><h5>L'affaire du siècle mais toujours pas de confirmation (1996-1999)</h5></li>
                                <p>L'été 1996 marque le début de la renaissance des Violet et Or. L'ancienne légende du club Jerry West, devenu Manager Général de l'équipe, conclut deux transactions qui vont relancer la mythique franchise et redonner espoir aux fans. Il arrache le pivot surpuissant Shaquille O'Neal au Magic d'Orlando sur le marché des transferts. Puis il réalise un coup de génie lors de la Draft, en expédiant son pivot titulaire de l'époque Vlade Divac aux Hornets de Charlotte en échange d'un jeune joueur arrivant directement de son lycée, Kobe Bryant.
                                    Dotés d'une équipe ultra-talentueuse mais qui manque parfois d'équilibre, les Lakers tâtonnent entre 1996 et 1999, et pêchent souvent par manque d'expérience lors des playoffs. Ils subissent ainsi de sévères échecs à ce niveau qui auront tendance à miner le moral des troupes.
                                    </p>
                                    <hr>
                            <li id="ancre7"><h5>La dynastie du nouveau millénaire et le duo Shaq & Kobe (1999-2004)</h5></li>
                                <p>En 1999, Jerry West trouve le chaînon manquant en nommant Phil Jackson entraîneur de l'équipe. Celui-ci, qui a décroché 6 titres de champion avec les Bulls de Chicago dans les années 1990, permet aux Lakers de franchir un cap. Avec un Shaquille O'Neal au sommet de son art, un Kobe Bryant qui explose au grand jour, et une bande de joueurs de complément tous aussi utiles les uns que les autres (Robert Horry, Derek Fisher, Rick Fox, Glen Rice…), les Lakers écrasent la saison régulière lors de laquelle ils décrochent 67 victoires. Les playoffs se révéleront plus compliqués que prévu, avec notamment une lutte épique en finale de Conférence Ouest face aux Trail Blazers de Portland : ils sont en effet contraints de disputer une 7e manche devant leur public alors qu'ils menaient 3-1 dans la série. Menés de 15 points à quelques minutes de la fin, les Lakers enflamment le Staples Center en signant un retour inimaginable et valident ainsi leur ticket pour la finale. Les Pacers de l'Indiana y seront écartés non sans mal en 6 manches. Les Lakers retrouvent enfin le sommet de la NBA après 12 ans de disette.
                                    La saison suivante est totalement différente. Une saison régulière chaotique fait naître des doutes sur la capacité des Lakers à conserver leur titre. Mais lors des playoffs, l'équipe se transforme soudainement en rouleau compresseur et lamine tous ses adversaires un par un. Finalement, les Lakers ne perdront qu'un seul match lors de ces playoffs 2000-2001 : le 1er match de la finale face aux Sixers de Philadelphie, emmenés par Allen Iverson. « Shaq and co » se ressaisissent vite et remportent les quatre prochains matchs, ce qui leur permet de remporter un deuxième titre consécutif.
                                    En 2001/02, les Lakers remportent un troisième titre de suite et réalisent (non sans mal) le Three-Peat (le fait de remporter trois titres de suite). Le principal obstacle sur leur parcours triomphal cette année-là est la finale de Conférence face à leur voisin californien, les Kings de Sacramento de Chris Webber. Les Lakers sortent par miracle indemnes de cette série en allant chercher la 7e manche à Sacramento. Le grand moment de cette série reste le tir à la dernière seconde de Robert Horry qui donne la victoire aux Lakers lors de la 4e manche, dans un Staples Center en fusion. La finale face aux Nets du New Jersey et leur meneur vedette Jason Kidd est un jeu d'enfant pour les Lakers, qui s'imposent 4-1.
                                    En 2002/03 les Lakers, quelque peu vieillissants, manquent le Four Ever et s'inclinent en demi-finales de Conférence face aux Spurs de San Antonio de Tim Duncan et du français Tony Parker. Les tensions dans l'équipe se renforcent.
                                    Vexés par cet échec, les dirigeants californiens souhaitent retrouver les sommets au plus vite et frappent un grand coup lors de l'intersaison en recrutant deux Hall of Famers en fin de carrière : Karl Malone et Gary Payton. Avec la présence de Kobe Bryant et Shaquille O'Neal, les Lakers possèdent alors une Dream Team qui fait trembler tous ses adversaires à l'entame de la Saison. Néanmoins, de nombreuses blessures et un manque de cohésion évident empêchent la machine Violet et Or de tourner à plein régime, ce qui leur vaut de perdre leur statut de favori au cours de la saison. Pourtant, ils retrouvent un effectif au complet à l'entame des playoffs et se voient offrir l'occasion de prendre leur revanche sur les Spurs en demi-finales de Conférence. Ils perdent les 2 premières manches à San Antonio mais remportent les 2 suivantes à domicile. Lors du 5e match, Tim Duncan pense donner la victoire aux Spurs sur un tir miraculeux. Cependant, avec 0.4 de secondes restant, Derek Fisher, sur un panier venu d'ailleurs, assomme les Spurs au buzzer. Ces derniers ne s'en remettront pas et perdront la série 4-2. les Lakers écartent ensuite les Timberwolves de Kevin Garnett en finale de conférence sur le score de 4-1. Opposés en finale aux Pistons de Détroit, les Lakers sont grandissimes favoris face à une équipe quasiment vierge d'expérience à ce niveau. Cependant, tout ne va pas comme prévu : les Lakers tombent de haut en perdant le 1er match devant leur public. Ils arrachent le 2e par miracle grâce à un tir au buzzer de Kobe Bryant pour envoyer le match en prolongation. Cependant, l'équipe sombre définitivement sur le parquet des Pistons. Le vieux sorcier Larry Brown, entraîneur de Détroit, a bâti un collectif parfaitement huilé et basé sur une défense de fer, en opposition totale avec la pléiade de stars des Lakers. Les conflits internes ressortent au plus mauvais moment et la blessure de Karl Malone n'arrange pas les choses. Les Lakers étouffés par les Pistons chutent 3 fois d'affilée à Détroit et s'inclinent 4-1.</p>
                                    <hr>
                            <li id="ancre8"><h5>Les Lakers en perte de vitesse : L'ère « post-Shaq » (2004-2007)</h5></li>
                                    <img class="col-6 img-fluid" src="../images/ShaqKobe.jpg" class="rounded">
                                <p>Cette défaite marque la fin d'une dynastie chez les Angelinos. Les deux stars O'Neal et Bryant ne peuvent plus cohabiter et le manager général Mitch Kupchak envoie O'Neal au Heat de Miami en échange de Lamar Odom, Caron Butler et Brian Grant. Malone, Payton et Phil Jackson quittent également les Lakers, qui espèrent se reconstruire autour de Kobe Bryant.
                                    Pour mener à bien cette reconstruction, les Lakers choisissent pour la saison 2004-2005 l'entraîneur Rudy Tomjanovich, deux fois champion avec les Rockets de Houston au milieu des années 1990. Tomjanovich est victime d'ennuis de santé et démissionne en cours de saison. Les Lakers s'effondrent après un début de saison honnête et ratent les playoffs pour la première fois depuis 1994.
                                    Déboussolé, le président Jerry Buss parvient à convaincre Phil Jackson de reprendre les rênes de l'équipe à l'entame de la saison 2005-06. Avec une équipe rajeunie et plus compacte, les Lakers remportent 45 matches et retrouvent les playoffs, emmenés par un Kobe Bryant stratosphérique, qui marque 35,5 points par match avec une pointe à 81 face aux Raptors de Toronto. Au premier tour des playoffs les Lakers passent tout près de faire tomber l'un des grands favoris, les Suns de Phoenix. Après avoir mené 3-1 dans la série à la suite notamment d'une fin de match incroyable lors du quatrième match, durant lequel Kobe Bryant donne la victoire à son équipe à la dernière seconde de la prolongation. Cependant, les Lakers se voient rejoindre à 3-3 en s'inclinant à domicile lors de la 6e rencontre, durant laquelle Tim Thomas arrache la prolongation sur un 3 points à la dernière seconde. Les Angelinos sont ensuite largement dominés lors de la 7e manche à Phoenix.
                                    Ils débutent ainsi la saison suivante plein d'espoir et entretiennent cet espoir en réalisant un très bon début de saison. Mais au grand désarroi d'un Kobe Bryant pourtant égal à lui-même (avec une série de quatre matches consécutifs à 50 points ou plus), les Lakers se désintègrent au fur et à mesure de la saison et finissent avec 42 victoires sur 81 matches. Ils se qualifient in extremis pour les playoffs où ils retrouvent les Suns au premier tour, mais sont battus 4-1. Irrité par cette saison décevante, Kobe Bryant fait pression en demandant à être transféré pendant l'été, avant de se rétracter.
                                    À l'entame de la nouvelle saison, l'incertitude règne encore quant à l'avenir de Kobe au sein de la formation californienne. Les dirigeants veulent encore croire que cette équipe peut retrouver les sommets, et misent sur l'éclosion du prometteur pivot Andrew Bynum et le retour d'un membre clé de la dynastie des Lakers, Derek Fisher, pour apaiser les velléités de départ de Bryant et relancer la franchise. Malgré un calendrier 2007-2008 difficile, une alchimie au plus mal et une ambiance morose, les Lakers réussissent leur début de saison en affichant un bilan de sept victoires pour cinq défaites alors que tous les analystes pensaient que leur bilan serait négatif après dix matchs. Dans ces sept victoires, Los Angeles a battu les Suns chez eux (119-98), le Jazz, les Pistons et les Rockets qui sont toutes des franchises qui prétendent au titre.</p>
                                    <hr>
                            <li id="ancre9"><h5>Le retour du succès de l'équipe : L'ère Bryant-Gasol (2007-2011)</h5></li>
                                <img class="col-4 img-fluid" src="../images/kobegasol.jpg" class="rounded">
                                <p>Alors qu'ils semblaient déjà avoir retrouvé une alchimie grâce à un Kobe Bryant altruiste, un état de forme exceptionnel de la part des joueurs du banc (Jordan Farmar, Andrew Bynum, Ronny Turiaf) et à l'émergence de Lamar Odom, les Lakers se positionnent maintenant comme un sérieux concurrent au titre après avoir échangé le 1er février 2008 Kwame Brown, deux premiers tours de draft et les droits de draft de Marc Gasol contre son frère Pau Gasol, en provenance des Grizzlies de Memphis. L'alchimie entre Kobe Bryant et Pau Gasol semble avoir pris directement et les victoires s'enchaînent : 10 victoires de rang, 18 victoires sur 23 matchs disputés6,7.
                                    Cette série exceptionnelle leur permet d'obtenir la tête de la conférence ouest, malgré de nombreux blessés (Pau Gasol, Andrew Bynum, Trevor Ariza et Chris Mihm), en fin de saison régulière. Leur bilan (57-25) est le meilleur depuis quatre ans. Ils disposent facilement des Nuggets de Denver au premier tour des playoffs (4-0), puis difficilement du Jazz de l'Utah (4-2), et enfin des champions en titre les Spurs 4 à 1, ce qui leur permet de se qualifier pour les finales. Les finales NBA 2008 sont remportées par les Celtics de Boston 4 victoires à 28.
                                    Les Lakers entament la saison 2008-2009 en enchaînant les victoires. Avec le retour de blessure d'Andrew Bynum qui avait manqué les playoffs et les finales, Phil Jackson replace Lamar Odom en sixième homme. Ils terminent la saison régulière avec un bilan de 65 victoires pour 17 défaites, le meilleur de la conférence Ouest, à une victoire seulement du meilleur bilan NBA, celui des Cavaliers de Cleveland. Pendant les playoffs, les Lakers éliminent successivement le Jazz de l'Utah (4-1), les Rockets de Houston (4-3) et en finale de conférence Ouest, les Nuggets de Denver (4-2). Ils disputeront donc les finales NBA 2009 face au Magic d'Orlando.
                                    Les Lakers remportent cette série 4-1 et remportent ainsi leur 15e titre de champion, le deuxième plus grand total après les 17 titres des Celtics de Boston. Kobe Bryant est élu National Basketball Association Finals Most Valuable Player Award, MVP des Finales. Kobe Bryant et Derek Fisher deviennent les joueurs en activité les plus titrés (4 titres) avec Shaquille O'Neal et Tim Duncan (4 titres). Phil Jackson devient l'entraîneur le plus titré avec 10 titres de champion NBA (6 avec les Bulls, 4 avec les Lakers).
                                    Durant la saison 2009-2010, les Lakers se renforcent en échangeant Ron Artest des Rockets de Houston contre Trevor Ariza et terminent premiers de la Conférence Ouest avec un bilan de 57 victoires pour 25 défaites, soit le meilleur bilan de la conférence Ouest pour la 3e année consécutive. Au premier tour des playoffs, ils éliminent le Thunder d'Oklahoma City quatre victoires à deux et enchaînent face au Jazz de l'Utah 4-0. Pour les finales de la Conférence Ouest, ils se retrouvent contre les Suns de Phoenix qu'ils battent 4 manches à 2. En finale NBA, ils rencontrent pour la 12e fois à ce stade de la compétition les Celtics de Boston et les battent 4 manches à 3 au bout du 7e match joué au Staples Center, le 16e titre de l'histoire de la franchise. Ils établissent un back-to-back après leur titre en 2009, Kobe Bryant et Derek Fisher deviennent les seuls joueurs en activité les plus titrés (5 titres) en remportant leur 5e titre personnel, tandis que Phil Jackson emporte sa 11e bague.
                                    Durant l'intersaison 2010, les Lakers réalisent un bon recrutement avec les arrivées de Matt Barnes et de Steve Blake.
                                    À la suite de la retraite de Shaquille O'Neal, les Lakers décident de lui rendre hommage en retirant son no 34 qui est hissé en haut du Staples Center. O'Neal a passé huit saisons à Los Angeles (1996-2004) et y a gagné trois de ses quatre bagues de champion.
                                    Après une saison peu convaincante pour les Lakers, ils se retrouvent deuxièmes de la Conférence Ouest et affrontent au premier tour des playoffs les Hornets de la Nouvelle-Orleans. Les Lakers terminent cette série difficilement sur le score de 4-2. Pour le deuxième tour ils se retrouvent face aux Mavericks de Dallas. Ils se font éliminer sèchement 4-0 après une humiliation au match 4 (122-86). Phil Jackson l'entraîneur voit son quatrième « Threepeat » lui passer sous le nez dès le deuxième tour. Toute la communauté NBA attendait une confrontation entre les Lakers et un des trois « monstres » de la Conférence Est : le Heat de Miami, les Celtics de Boston et les Bulls de Chicago. Il faut attendre l'année prochaine pour voir la ville des Anges briller à nouveau.</p>
                                    <hr>
                                    <li id="ancre10"><h5>La reconstruction : Nash, Howard et D'Antoni (2012-2016)</h5></li>
                                    <img class="col-6 img-fluid" src="../images/antoni.jpg" class="rounded">
                                <p>Le manager général des Lakers applique dès le mois d'août ses consignes. Dwight Howard, le meilleur pivot de la ligue et triple meilleur défenseur de la NBA, arrive dans un échange à quatre équipes ou Andrew Bynum atterrit chez les Sixers de Philadelphie. Antawn Jamison et Jodie Meeks arrivent également pour la franchise en août. Début juillet, c'est le meneur canadien Steve Nash qui avait signé pour 3 ans, réalisant un 5 majeur de rêve pour les Angelinos : Nash - Bryant - World Peace - Gasol - Howard. Avant même le début de la saison, les Lakers se positionnent en candidats pour la succession du Heat de Miami pour le titre du championnat9,10. Toutefois, avec un bilan de huit défaites en autant de rencontres en pré-saison et d'une victoire pour cinq défaites en saison régulière, les résultats ne sont pas à la hauteur des objectifs attendus. Aussi, le 9 novembre 2012, Mike Brown est démis de son poste, Bernie Bickerstaff, son assistant, devenant alors entraîneur par intérim11. Après quelques jours, les Lakers engagent Mike D'Antoni comme nouveau head coach. Les Lakers connaissent une saison très compliquée et Kobe Bryant se blesse en fin de saison régulière lors d'un match contre les Warriors de Golden State remporté 118-116 par les Lakers. Celui-ci s'est rompu le tendon d'Achille et laisse penser qu'il pourrait être indisponible pendant un an. Mais son état s'améliore plus vite que prévu et il manque uniquement le début de saison 2013-2014. Les Lakers se qualifient de justesse pour les Playoffs dans les derniers jours de la saison et finissent la saison régulière à la septième place de la conférence ouest avec un décevant bilan de 45 victoires pour 37 défaites. Au premier tour des Playoffs, les Lakers doivent se confronter aux Spurs de San Antonio de Tony Parker et se font éliminer sèchement 4-0. À la suite de cette élimination beaucoup de changements ont été effectués dans l'effectif de l'équipe. D'abord, Dwight Howard n'ayant signé que pour un an avec les Angelinos décide de ne pas poursuive l'aventure avec eux et quitte la Californie pour s'engager avec les Rockets de Houston. Metta World Peace, après 4 ans passés avec les Lakers (dont un titre NBA remporté en 2010 avec les Angelinos), quitte également la Californie pour rejoindre les Knicks de New York. Earl Clark, Chris Duhon, Devin Ebanks, Andrew Goudelock, Antawn Jamison, et Darius Moris quittent également les Lakers qui doivent tout reconstruire à nouveau pour la nouvelle saison.
                                    Les Lakers connaissent un début de saison 2014-2015 catastrophique. Après une nouvelle défaite concédée sur le parquet des Warriors de Golden State (136-115) le 16 novembre malgré 44 points de Kobe Bryant, les Lakers affichent un bilan d'une victoire et neuf défaites en dix matchs, le pire début de saison de l'histoire de la franchise12.
                                    Les Lakers obtiennent le 2e choix de la Draft 2015 de la NBA et choisissent le prometteur meneur D'Angelo Russell qui forme une ligne arrière complémentaire avec Jordan Clarkson ou Kobe Bryant.
                                    La saison 2015-2016 commence sur les mêmes bases que la précédente, avec 4 défaites consécutives. Après un mois de compétition, les Lakers présentent un bilan peu flatteur de deux victoires pour quatorze défaites. Finalement, le 29 novembre 2015 Kobe Bryant annonce que cette saison est sa dernière. La saison des Lakers prend alors plus ou moins la forme d'une tournée d'adieu, de nombreux hommages étant rendus au joueur vedette des Lakers par l'ensemble des franchises. Pour son dernier match, Kobe réalise une performance exceptionnelle en inscrivant 60 points, record de la saison, et en parvenant à faire gagner son équipe face au Jazz de l'Utah13. Néanmoins, malgré ce dernier coup d'éclat, les Lakers finissent la saison avec un bilan de 17 victoires pour 65 défaites, soit le deuxième pire bilan de la ligue (après les 76ers de Philadelphie) et le pire bilan de l'histoire de la franchise.</p>
                                    <hr>
                            <li id="ancre11"><h5>Les Lakers de LeBron James (depuis 2018)</h5></li>
                                <img class="col-6 img-fluid" src="../images/Lebron.jpg" class="rounded">
                                <p>Le 1er juillet 2018, LeBron James, étant free-agent, quitte les Cavaliers de Cleveland pour rejoindre les Lakers. Il signe un contrat de 154 millions de dollars sur quatre ans18. LeBron James est alors immédiatement rejoint par l'arrière Lance Stephenson et le pivot JaVale McGee19. Le 3 juillet, Rajon Rondo signe également au Lakers pour un contrat d'un an pour 9 millions de dollars20.
                                    La saison 2018-2019, première de l'ère LeBron James, est compliquée pour l'équipe. Avec notamment la blessure de LeBron le 25 décembre qui l'éloigne des parquets pour plus d'un mois21. La saison est aussi marqué lors de la trade dead-line par les rumeurs de transferts pour récupérer Anthony Davis (basket-ball). Elles mettent à mal la cohésion du groupe déjà sous tension22. Rumeurs démenties très maladroitement par la propriétaire du club Jeanie Buss parlant de "fake news"23. Juste avant la fin de la saison régulière, le GM Magic Johnson annonce, lors d'une conférence de presse d'avant match, quitter le club24.          
                                    A la fin de la saison 2018-2019, conclue par une non qualification aux playoffs, l'entraineur Luke Walton et la franchise se mettent d'accord sur les modalités de départ de l'entraîneur25. Son successeur, Frank Vogel est quant à lui nommé le 12 mai 201926. Les fameuses rumeurs quant à l'arrivée possible d'Anthony Davis se concrétisent le 15 juin. Les Lakers, en échange du joueur, envoient aux Pelicans de La Nouvelle-Orléans 3 premiers tours de Draft dont celui de 2019, Lonzo Ball, Josh Hart et Brandon Ingram27.                       
                                    L'attraction James-Davis fonctionne également grâce aux nombreuses recrues venues de la Free Agency comme Danny Green, récent champion NBA 2019 avec les Raptors de Toronto. L'effectif se voit ajouter Avery Bradley, ainsi que Quinn Cook, ancien meneur des Warriors de Golden State. Le duo LeBron-Davis est complémentaire et les Lakers commencent leur saison avec un 12-2, ce qui n'était plus arrivé depuis 10 ans, époque glorieuse de Kobe Bryant. LeBron fait encore parler par ses statistiques lors du match face au Thunder d'Oklahoma City, en réalisant un triple double, lui permettant d'ajouter à son palmarès un nouveau record parmi tant d'autres, soit réaliser un triple-double face aux 30 équipes de la NBA28. La saison 2019-2020 des Lakers est endeuillée par la tragique disparition de l'ancienne superstar Kobe Bryant, dans un accident d'hélicoptère, accompagné de sa fille et d'autres passagers29.
                                    La fin de la saison 2019-2020 est marquée par la victoire 4-2 des Lakers NBA en finales contre le Heat de Miami ainsi que le 4ème trophée de MVP des finales remporté par LeBron James</p>
                                    <hr>
                        </ol>
                        <li id="ancre12"><h5>Palmarès</h5></li>
                            <img src="../images/BanniereLA.jpg" alt="Bannière Lakers">
                                    <ul>
                                        <li><h6>Champion de Conférence </h6></li>
                                        <p>Champion de Conférence (32) : 1949, 1950, 1952, 1953, 1954, 1959, 1962, 1963, 1965, 1966, 1968, 1969, 1970, 1972, 1973, 1980, 1982, 1983, 1984, 1985, 1987, 1988, 1989, 1991, 2000, 2001, 2002, 2004, 2008, 2009, 2010 et 2020.</p>
                                        <li><h6>Champion de division pacifique</h6></li>
                                        <p>Champion de la Division Pacifique (24) : 1971, 1972, 1973, 1974, 1977, 1980, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 2000, 2001, 2002, 2004, 2008, 2009, 2010, 2011, 2012 et 2020.</p>
                                        <li><h6>Champion NBA</h6></li>
                                        <p>Champion NBA (17) :
                                            1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, 2010 et 2020.</p>
                                    </ul>
                                     <hr>
                    </ol>
                </div>
            </div>
        </div>
        <!--C'est le pied de page-->
        <div class="container-fluid">
        <footer id="f"> 
            <p>Copyright 2022©<a href="#ancre13">Remonter en haut</a><br>Site Web créé par des éléves de BTS SIO 1:<br><a href="mailto:Medhy.Djelloul@stcharles-stecroix.org">Medhy Djelloul</a> et <a href="mailto:arkani.ouateko-dady@stcharles-stecroix.org">Brad Ouateko Dady.</a> </p>
          </footer>
        </div>
        <!--C'est le lien Js-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>